<?php

return [
  ['iso' => 'AD', 'name' => 'Andorra', 'native' => 'Andorra', 'emoji' => '🇦🇩'],
  ['iso' => 'AE', 'name' => 'United Arab Emirates', 'native' => 'الإمارات العربية المتحدة', 'emoji' => '🇦🇪'],
  ['iso' => 'AF', 'name' => 'Afghanistan', 'native' => 'افغانستان', 'emoji' => '🇦🇫'],
  ['iso' => 'AG', 'name' => 'Antigua and Barbuda', 'native' => 'Antigua and Barbuda', 'emoji' => '🇦🇬'],
  ['iso' => 'AI', 'name' => 'Anguilla', 'native' => 'Anguilla', 'emoji' => '🇦🇮'],
  ['iso' => 'AL', 'name' => 'Albania', 'native' => 'Shqipëria', 'emoji' => '🇦🇱'],
  ['iso' => 'AM', 'name' => 'Armenia', 'native' => 'Հայաստան', 'emoji' => '🇦🇲'],
  ['iso' => 'AO', 'name' => 'Angola', 'native' => 'Angola', 'emoji' => '🇦🇴'],
  ['iso' => 'AQ', 'name' => 'Antarctica', 'native' => 'Antarctica', 'emoji' => '🇦🇶'],
  ['iso' => 'AR', 'name' => 'Argentina', 'native' => 'Argentina', 'emoji' => '🇦🇷'],
  ['iso' => 'AS', 'name' => 'American Samoa', 'native' => 'American Samoa', 'emoji' => '🇦🇸'],
  ['iso' => 'AT', 'name' => 'Austria', 'native' => 'Österreich', 'emoji' => '🇦🇹'],
  ['iso' => 'AU', 'name' => 'Australia', 'native' => 'Australia', 'emoji' => '🇦🇺'],
  ['iso' => 'AW', 'name' => 'Aruba', 'native' => 'Aruba', 'emoji' => '🇦🇼'],
  ['iso' => 'AX', 'name' => 'Åland Islands', 'native' => 'Åland', 'emoji' => '🇦🇽'],
  ['iso' => 'AZ', 'name' => 'Azerbaijan', 'native' => 'Azərbaycan', 'emoji' => '🇦🇿'],
  ['iso' => 'BA', 'name' => 'Bosnia and Herzegovina', 'native' => 'Bosna i Hercegovina', 'emoji' => '🇧🇦'],
  ['iso' => 'BB', 'name' => 'Barbados', 'native' => 'Barbados', 'emoji' => '🇧🇧'],
  ['iso' => 'BD', 'name' => 'Bangladesh', 'native' => 'বাংলাদেশ', 'emoji' => '🇧🇩'],
  ['iso' => 'BE', 'name' => 'Belgium', 'native' => 'België', 'emoji' => '🇧🇪'],
  ['iso' => 'BF', 'name' => 'Burkina Faso', 'native' => 'Burkina Faso', 'emoji' => '🇧🇫'],
  ['iso' => 'BG', 'name' => 'Bulgaria', 'native' => 'България', 'emoji' => '🇧🇬'],
  ['iso' => 'BH', 'name' => 'Bahrain', 'native' => 'البحرين', 'emoji' => '🇧🇭'],
  ['iso' => 'BI', 'name' => 'Burundi', 'native' => 'Burundi', 'emoji' => '🇧🇮'],
  ['iso' => 'BJ', 'name' => 'Benin', 'native' => 'Bénin', 'emoji' => '🇧🇯'],
  ['iso' => 'BL', 'name' => 'Saint Barthélemy', 'native' => 'Saint-Barthélemy', 'emoji' => '🇧🇱'],
  ['iso' => 'BM', 'name' => 'Bermuda', 'native' => 'Bermuda', 'emoji' => '🇧🇲'],
  ['iso' => 'BN', 'name' => 'Brunei', 'native' => 'Brunei', 'emoji' => '🇧🇳'],
  ['iso' => 'BO', 'name' => 'Bolivia', 'native' => 'Bolivia', 'emoji' => '🇧🇴'],
  ['iso' => 'BQ', 'name' => 'Caribbean Netherlands', 'native' => 'Caribbean Netherlands', 'emoji' => '🇧🇶'],
  ['iso' => 'BR', 'name' => 'Brazil', 'native' => 'Brasil', 'emoji' => '🇧🇷'],
  ['iso' => 'BS', 'name' => 'Bahamas', 'native' => 'Bahamas', 'emoji' => '🇧🇸'],
  ['iso' => 'BT', 'name' => 'Bhutan', 'native' => 'འབྲུག', 'emoji' => '🇧🇹'],
  ['iso' => 'BV', 'name' => 'Bouvet Island', 'native' => 'Bouvetøya', 'emoji' => '🇧🇻'],
  ['iso' => 'BW', 'name' => 'Botswana', 'native' => 'Botswana', 'emoji' => '🇧🇼'],
  ['iso' => 'BY', 'name' => 'Belarus', 'native' => 'Беларусь', 'emoji' => '🇧🇾'],
  ['iso' => 'BZ', 'name' => 'Belize', 'native' => 'Belize', 'emoji' => '🇧🇿'],
  ['iso' => 'CA', 'name' => 'Canada', 'native' => 'Canada', 'emoji' => '🇨🇦'],
  ['iso' => 'CC', 'name' => 'Cocos Islands', 'native' => 'Cocos (Keeling) Islands', 'emoji' => '🇨🇨'],
  ['iso' => 'CD', 'name' => 'DR Congo', 'native' => 'République démocratique du Congo', 'emoji' => '🇨🇩'],
  ['iso' => 'CF', 'name' => 'Central African Republic', 'native' => 'République centrafricaine', 'emoji' => '🇨🇫'],
  ['iso' => 'CG', 'name' => 'Republic of the Congo', 'native' => 'République du Congo', 'emoji' => '🇨🇬'],
  ['iso' => 'CH', 'name' => 'Switzerland', 'native' => 'Schweiz', 'emoji' => '🇨🇭'],
  ['iso' => 'CI', 'name' => 'Côte d\'Ivoire', 'native' => 'Côte d\'Ivoire', 'emoji' => '🇨🇮'],
  ['iso' => 'CK', 'name' => 'Cook Islands', 'native' => 'Cook Islands', 'emoji' => '🇨🇰'],
  ['iso' => 'CL', 'name' => 'Chile', 'native' => 'Chile', 'emoji' => '🇨🇱'],
  ['iso' => 'CM', 'name' => 'Cameroon', 'native' => 'Cameroun', 'emoji' => '🇨🇲'],
  ['iso' => 'CN', 'name' => 'China', 'native' => '中国', 'emoji' => '🇨🇳'],
  ['iso' => 'CO', 'name' => 'Colombia', 'native' => 'Colombia', 'emoji' => '🇨🇴'],
  ['iso' => 'CR', 'name' => 'Costa Rica', 'native' => 'Costa Rica', 'emoji' => '🇨🇷'],
  ['iso' => 'CU', 'name' => 'Cuba', 'native' => 'Cuba', 'emoji' => '🇨🇺'],
  ['iso' => 'CV', 'name' => 'Cape Verde', 'native' => 'Cabo Verde', 'emoji' => '🇨🇻'],
  ['iso' => 'CW', 'name' => 'Curaçao', 'native' => 'Curaçao', 'emoji' => '🇨🇼'],
  ['iso' => 'CX', 'name' => 'Christmas Island', 'native' => 'Christmas Island', 'emoji' => '🇨🇽'],
  ['iso' => 'CY', 'name' => 'Cyprus', 'native' => 'Κύπρος', 'emoji' => '🇨🇾'],
  ['iso' => 'CZ', 'name' => 'Czech Republic', 'native' => 'Česká republika', 'emoji' => '🇨🇿'],
  ['iso' => 'DE', 'name' => 'Germany', 'native' => 'Deutschland', 'emoji' => '🇩🇪'],
  ['iso' => 'DJ', 'name' => 'Djibouti', 'native' => 'Djibouti', 'emoji' => '🇩🇯'],
  ['iso' => 'DK', 'name' => 'Denmark', 'native' => 'Danmark', 'emoji' => '🇩🇰'],
  ['iso' => 'DM', 'name' => 'Dominica', 'native' => 'Dominica', 'emoji' => '🇩🇲'],
  ['iso' => 'DO', 'name' => 'Dominican Republic', 'native' => 'República Dominicana', 'emoji' => '🇩🇴'],
  ['iso' => 'DZ', 'name' => 'Algeria', 'native' => 'الجزائر', 'emoji' => '🇩🇿'],
  ['iso' => 'EC', 'name' => 'Ecuador', 'native' => 'Ecuador', 'emoji' => '🇪🇨'],
  ['iso' => 'EE', 'name' => 'Estonia', 'native' => 'Eesti', 'emoji' => '🇪🇪'],
  ['iso' => 'EG', 'name' => 'Egypt', 'native' => 'مصر', 'emoji' => '🇪🇬'],
  ['iso' => 'EH', 'name' => 'Western Sahara', 'native' => 'الصحراء الغربية', 'emoji' => '🇪🇭'],
  ['iso' => 'ER', 'name' => 'Eritrea', 'native' => 'ኤርትራ', 'emoji' => '🇪🇷'],
  ['iso' => 'ES', 'name' => 'Spain', 'native' => 'España', 'emoji' => '🇪🇸'],
  ['iso' => 'ET', 'name' => 'Ethiopia', 'native' => 'ኢትዮጵያ', 'emoji' => '🇪🇹'],
  ['iso' => 'FI', 'name' => 'Finland', 'native' => 'Suomi', 'emoji' => '🇫🇮'],
  ['iso' => 'FJ', 'name' => 'Fiji', 'native' => 'Fiji', 'emoji' => '🇫🇯'],
  ['iso' => 'FK', 'name' => 'Falkland Islands', 'native' => 'Falkland Islands', 'emoji' => '🇫🇰'],
  ['iso' => 'FM', 'name' => 'Micronesia', 'native' => 'Micronesia', 'emoji' => '🇫🇲'],
  ['iso' => 'FO', 'name' => 'Faroe Islands', 'native' => 'Føroyar', 'emoji' => '🇫🇴'],
  ['iso' => 'FR', 'name' => 'France', 'native' => 'France', 'emoji' => '🇫🇷'],
  ['iso' => 'GA', 'name' => 'Gabon', 'native' => 'Gabon', 'emoji' => '🇬🇦'],
  ['iso' => 'GB', 'name' => 'United Kingdom', 'native' => 'United Kingdom', 'emoji' => '🇬🇧'],
  ['iso' => 'GD', 'name' => 'Grenada', 'native' => 'Grenada', 'emoji' => '🇬🇩'],
  ['iso' => 'GE', 'name' => 'Georgia', 'native' => 'საქართველო', 'emoji' => '🇬🇪'],
  ['iso' => 'GF', 'name' => 'French Guiana', 'native' => 'Guyane française', 'emoji' => '🇬🇫'],
  ['iso' => 'GG', 'name' => 'Guernsey', 'native' => 'Guernsey', 'emoji' => '🇬🇬'],
  ['iso' => 'GH', 'name' => 'Ghana', 'native' => 'Ghana', 'emoji' => '🇬🇭'],
  ['iso' => 'GI', 'name' => 'Gibraltar', 'native' => 'Gibraltar', 'emoji' => '🇬🇮'],
  ['iso' => 'GL', 'name' => 'Greenland', 'native' => 'Kalaallit Nunaat', 'emoji' => '🇬🇱'],
  ['iso' => 'GM', 'name' => 'Gambia', 'native' => 'Gambia', 'emoji' => '🇬🇲'],
  ['iso' => 'GN', 'name' => 'Guinea', 'native' => 'Guinée', 'emoji' => '🇬🇳'],
  ['iso' => 'GP', 'name' => 'Guadeloupe', 'native' => 'Guadeloupe', 'emoji' => '🇬🇵'],
  ['iso' => 'GQ', 'name' => 'Equatorial Guinea', 'native' => 'Guinea Ecuatorial', 'emoji' => '🇬🇶'],
  ['iso' => 'GR', 'name' => 'Greece', 'native' => 'Ελλάδα', 'emoji' => '🇬🇷'],
  ['iso' => 'GS', 'name' => 'South Georgia', 'native' => 'South Georgia', 'emoji' => '🇬🇸'],
  ['iso' => 'GT', 'name' => 'Guatemala', 'native' => 'Guatemala', 'emoji' => '🇬🇹'],
  ['iso' => 'GU', 'name' => 'Guam', 'native' => 'Guam', 'emoji' => '🇬🇺'],
  ['iso' => 'GW', 'name' => 'Guinea-Bissau', 'native' => 'Guiné-Bissau', 'emoji' => '🇬🇼'],
  ['iso' => 'GY', 'name' => 'Guyana', 'native' => 'Guyana', 'emoji' => '🇬🇾'],
  ['iso' => 'HK', 'name' => 'Hong Kong', 'native' => '香港', 'emoji' => '🇭🇰'],
  ['iso' => 'HM', 'name' => 'Heard Island', 'native' => 'Heard Island and McDonald Islands', 'emoji' => '🇭🇲'],
  ['iso' => 'HN', 'name' => 'Honduras', 'native' => 'Honduras', 'emoji' => '🇭🇳'],
  ['iso' => 'HR', 'name' => 'Croatia', 'native' => 'Hrvatska', 'emoji' => '🇭🇷'],
  ['iso' => 'HT', 'name' => 'Haiti', 'native' => 'Haïti', 'emoji' => '🇭🇹'],
  ['iso' => 'HU', 'name' => 'Hungary', 'native' => 'Magyarország', 'emoji' => '🇭🇺'],
  ['iso' => 'ID', 'name' => 'Indonesia', 'native' => 'Indonesia', 'emoji' => '🇮🇩'],
  ['iso' => 'IE', 'name' => 'Ireland', 'native' => 'Éire', 'emoji' => '🇮🇪'],
  ['iso' => 'IL', 'name' => 'Israel', 'native' => 'יִשְׂרָאֵל', 'emoji' => '🇮🇱'],
  ['iso' => 'IM', 'name' => 'Isle of Man', 'native' => 'Isle of Man', 'emoji' => '🇮🇲'],
  ['iso' => 'IN', 'name' => 'India', 'native' => 'भारत', 'emoji' => '🇮🇳'],
  ['iso' => 'IO', 'name' => 'British Indian Ocean Territory', 'native' => 'British Indian Ocean Territory', 'emoji' => '🇮🇴'],
  ['iso' => 'IQ', 'name' => 'Iraq', 'native' => 'العراق', 'emoji' => '🇮🇶'],
  ['iso' => 'IR', 'name' => 'Iran', 'native' => 'ایران', 'emoji' => '🇮🇷'],
  ['iso' => 'IS', 'name' => 'Iceland', 'native' => 'Ísland', 'emoji' => '🇮🇸'],
  ['iso' => 'IT', 'name' => 'Italy', 'native' => 'Italia', 'emoji' => '🇮🇹'],
  ['iso' => 'JE', 'name' => 'Jersey', 'native' => 'Jersey', 'emoji' => '🇯🇪'],
  ['iso' => 'JM', 'name' => 'Jamaica', 'native' => 'Jamaica', 'emoji' => '🇯🇲'],
  ['iso' => 'JO', 'name' => 'Jordan', 'native' => 'الأردن', 'emoji' => '🇯🇴'],
  ['iso' => 'JP', 'name' => 'Japan', 'native' => '日本', 'emoji' => '🇯🇵'],
  ['iso' => 'KE', 'name' => 'Kenya', 'native' => 'Kenya', 'emoji' => '🇰🇪'],
  ['iso' => 'KG', 'name' => 'Kyrgyzstan', 'native' => 'Кыргызстан', 'emoji' => '🇰🇬'],
  ['iso' => 'KH', 'name' => 'Cambodia', 'native' => 'កម្ពុជា', 'emoji' => '🇰🇭'],
  ['iso' => 'KI', 'name' => 'Kiribati', 'native' => 'Kiribati', 'emoji' => '🇰🇮'],
  ['iso' => 'KM', 'name' => 'Comoros', 'native' => 'جزر القمر', 'emoji' => '🇰🇲'],
  ['iso' => 'KN', 'name' => 'Saint Kitts and Nevis', 'native' => 'Saint Kitts and Nevis', 'emoji' => '🇰🇳'],
  ['iso' => 'KP', 'name' => 'North Korea', 'native' => '조선민주주의인민공화국', 'emoji' => '🇰🇵'],
  ['iso' => 'KR', 'name' => 'South Korea', 'native' => '대한민국', 'emoji' => '🇰🇷'],
  ['iso' => 'KW', 'name' => 'Kuwait', 'native' => 'الكويت', 'emoji' => '🇰🇼'],
  ['iso' => 'KY', 'name' => 'Cayman Islands', 'native' => 'Cayman Islands', 'emoji' => '🇰🇾'],
  ['iso' => 'KZ', 'name' => 'Kazakhstan', 'native' => 'Қазақстан', 'emoji' => '🇰🇿'],
  ['iso' => 'LA', 'name' => 'Laos', 'native' => 'ລາວ', 'emoji' => '🇱🇦'],
  ['iso' => 'LB', 'name' => 'Lebanon', 'native' => 'لبنان', 'emoji' => '🇱🇧'],
  ['iso' => 'LC', 'name' => 'Saint Lucia', 'native' => 'Saint Lucia', 'emoji' => '🇱🇨'],
  ['iso' => 'LI', 'name' => 'Liechtenstein', 'native' => 'Liechtenstein', 'emoji' => '🇱🇮'],
  ['iso' => 'LK', 'name' => 'Sri Lanka', 'native' => 'ශ්‍රී ලංකාව', 'emoji' => '🇱🇰'],
  ['iso' => 'LR', 'name' => 'Liberia', 'native' => 'Liberia', 'emoji' => '🇱🇷'],
  ['iso' => 'LS', 'name' => 'Lesotho', 'native' => 'Lesotho', 'emoji' => '🇱🇸'],
  ['iso' => 'LT', 'name' => 'Lithuania', 'native' => 'Lietuva', 'emoji' => '🇱🇹'],
  ['iso' => 'LU', 'name' => 'Luxembourg', 'native' => 'Luxembourg', 'emoji' => '🇱🇺'],
  ['iso' => 'LV', 'name' => 'Latvia', 'native' => 'Latvija', 'emoji' => '🇱🇻'],
  ['iso' => 'LY', 'name' => 'Libya', 'native' => 'ليبيا', 'emoji' => '🇱🇾'],
  ['iso' => 'MA', 'name' => 'Morocco', 'native' => 'المغرب', 'emoji' => '🇲🇦'],
  ['iso' => 'MC', 'name' => 'Monaco', 'native' => 'Monaco', 'emoji' => '🇲🇨'],
  ['iso' => 'MD', 'name' => 'Moldova', 'native' => 'Moldova', 'emoji' => '🇲🇩'],
  ['iso' => 'ME', 'name' => 'Montenegro', 'native' => 'Crna Gora', 'emoji' => '🇲🇪'],
  ['iso' => 'MF', 'name' => 'Saint Martin', 'native' => 'Saint-Martin', 'emoji' => '🇲🇫'],
  ['iso' => 'MG', 'name' => 'Madagascar', 'native' => 'Madagasikara', 'emoji' => '🇲🇬'],
  ['iso' => 'MH', 'name' => 'Marshall Islands', 'native' => 'Marshall Islands', 'emoji' => '🇲🇭'],
  ['iso' => 'MK', 'name' => 'North Macedonia', 'native' => 'Северна Македонија', 'emoji' => '🇲🇰'],
  ['iso' => 'ML', 'name' => 'Mali', 'native' => 'Mali', 'emoji' => '🇲🇱'],
  ['iso' => 'MM', 'name' => 'Myanmar', 'native' => 'မြန်မာ', 'emoji' => '🇲🇲'],
  ['iso' => 'MN', 'name' => 'Mongolia', 'native' => 'Монгол', 'emoji' => '🇲🇳'],
  ['iso' => 'MO', 'name' => 'Macao', 'native' => '澳門', 'emoji' => '🇲🇴'],
  ['iso' => 'MP', 'name' => 'Northern Mariana Islands', 'native' => 'Northern Mariana Islands', 'emoji' => '🇲🇵'],
  ['iso' => 'MQ', 'name' => 'Martinique', 'native' => 'Martinique', 'emoji' => '🇲🇶'],
  ['iso' => 'MR', 'name' => 'Mauritania', 'native' => 'موريتانيا', 'emoji' => '🇲🇷'],
  ['iso' => 'MS', 'name' => 'Montserrat', 'native' => 'Montserrat', 'emoji' => '🇲🇸'],
  ['iso' => 'MT', 'name' => 'Malta', 'native' => 'Malta', 'emoji' => '🇲🇹'],
  ['iso' => 'MU', 'name' => 'Mauritius', 'native' => 'Mauritius', 'emoji' => '🇲🇺'],
  ['iso' => 'MV', 'name' => 'Maldives', 'native' => 'ދިވެހިރާއްޖެ', 'emoji' => '🇲🇻'],
  ['iso' => 'MW', 'name' => 'Malawi', 'native' => 'Malawi', 'emoji' => '🇲🇼'],
  ['iso' => 'MX', 'name' => 'Mexico', 'native' => 'México', 'emoji' => '🇲🇽'],
  ['iso' => 'MY', 'name' => 'Malaysia', 'native' => 'Malaysia', 'emoji' => '🇲🇾'],
  ['iso' => 'MZ', 'name' => 'Mozambique', 'native' => 'Moçambique', 'emoji' => '🇲🇿'],
  ['iso' => 'NA', 'name' => 'Namibia', 'native' => 'Namibia', 'emoji' => '🇳🇦'],
  ['iso' => 'NC', 'name' => 'New Caledonia', 'native' => 'Nouvelle-Calédonie', 'emoji' => '🇳🇨'],
  ['iso' => 'NE', 'name' => 'Niger', 'native' => 'Niger', 'emoji' => '🇳🇪'],
  ['iso' => 'NF', 'name' => 'Norfolk Island', 'native' => 'Norfolk Island', 'emoji' => '🇳🇫'],
  ['iso' => 'NG', 'name' => 'Nigeria', 'native' => 'Nigeria', 'emoji' => '🇳🇬'],
  ['iso' => 'NI', 'name' => 'Nicaragua', 'native' => 'Nicaragua', 'emoji' => '🇳🇮'],
  ['iso' => 'NL', 'name' => 'Netherlands', 'native' => 'Nederland', 'emoji' => '🇳🇱'],
  ['iso' => 'NO', 'name' => 'Norway', 'native' => 'Norge', 'emoji' => '🇳🇴'],
  ['iso' => 'NP', 'name' => 'Nepal', 'native' => 'नेपाल', 'emoji' => '🇳🇵'],
  ['iso' => 'NR', 'name' => 'Nauru', 'native' => 'Nauru', 'emoji' => '🇳🇷'],
  ['iso' => 'NU', 'name' => 'Niue', 'native' => 'Niue', 'emoji' => '🇳🇺'],
  ['iso' => 'NZ', 'name' => 'New Zealand', 'native' => 'New Zealand', 'emoji' => '🇳🇿'],
  ['iso' => 'OM', 'name' => 'Oman', 'native' => 'عُمان', 'emoji' => '🇴🇲'],
  ['iso' => 'PA', 'name' => 'Panama', 'native' => 'Panamá', 'emoji' => '🇵🇦'],
  ['iso' => 'PE', 'name' => 'Peru', 'native' => 'Perú', 'emoji' => '🇵🇪'],
  ['iso' => 'PF', 'name' => 'French Polynesia', 'native' => 'Polynésie française', 'emoji' => '🇵🇫'],
  ['iso' => 'PG', 'name' => 'Papua New Guinea', 'native' => 'Papua New Guinea', 'emoji' => '🇵🇬'],
  ['iso' => 'PH', 'name' => 'Philippines', 'native' => 'Pilipinas', 'emoji' => '🇵🇭'],
  ['iso' => 'PK', 'name' => 'Pakistan', 'native' => 'پاکستان', 'emoji' => '🇵🇰'],
  ['iso' => 'PL', 'name' => 'Poland', 'native' => 'Polska', 'emoji' => '🇵🇱'],
  ['iso' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'native' => 'Saint-Pierre-et-Miquelon', 'emoji' => '🇵🇲'],
  ['iso' => 'PN', 'name' => 'Pitcairn Islands', 'native' => 'Pitcairn Islands', 'emoji' => '🇵🇳'],
  ['iso' => 'PR', 'name' => 'Puerto Rico', 'native' => 'Puerto Rico', 'emoji' => '🇵🇷'],
  ['iso' => 'PS', 'name' => 'Palestine', 'native' => 'فلسطين', 'emoji' => '🇵🇸'],
  ['iso' => 'PT', 'name' => 'Portugal', 'native' => 'Portugal', 'emoji' => '🇵🇹'],
  ['iso' => 'PW', 'name' => 'Palau', 'native' => 'Palau', 'emoji' => '🇵🇼'],
  ['iso' => 'PY', 'name' => 'Paraguay', 'native' => 'Paraguay', 'emoji' => '🇵🇾'],
  ['iso' => 'QA', 'name' => 'Qatar', 'native' => 'قطر', 'emoji' => '🇶🇦'],
  ['iso' => 'RE', 'name' => 'Réunion', 'native' => 'La Réunion', 'emoji' => '🇷🇪'],
  ['iso' => 'RO', 'name' => 'Romania', 'native' => 'România', 'emoji' => '🇷🇴'],
  ['iso' => 'RS', 'name' => 'Serbia', 'native' => 'Србија', 'emoji' => '🇷🇸'],
  ['iso' => 'RU', 'name' => 'Russia', 'native' => 'Россия', 'emoji' => '🇷🇺'],
  ['iso' => 'RW', 'name' => 'Rwanda', 'native' => 'Rwanda', 'emoji' => '🇷🇼'],
  ['iso' => 'SA', 'name' => 'Saudi Arabia', 'native' => 'السعودية', 'emoji' => '🇸🇦'],
  ['iso' => 'SB', 'name' => 'Solomon Islands', 'native' => 'Solomon Islands', 'emoji' => '🇸🇧'],
  ['iso' => 'SC', 'name' => 'Seychelles', 'native' => 'Seychelles', 'emoji' => '🇸🇨'],
  ['iso' => 'SD', 'name' => 'Sudan', 'native' => 'السودان', 'emoji' => '🇸🇩'],
  ['iso' => 'SE', 'name' => 'Sweden', 'native' => 'Sverige', 'emoji' => '🇸🇪'],
  ['iso' => 'SG', 'name' => 'Singapore', 'native' => 'Singapore', 'emoji' => '🇸🇬'],
  ['iso' => 'SH', 'name' => 'Saint Helena', 'native' => 'Saint Helena', 'emoji' => '🇸🇭'],
  ['iso' => 'SI', 'name' => 'Slovenia', 'native' => 'Slovenija', 'emoji' => '🇸🇮'],
  ['iso' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'native' => 'Svalbard og Jan Mayen', 'emoji' => '🇸🇯'],
  ['iso' => 'SK', 'name' => 'Slovakia', 'native' => 'Slovensko', 'emoji' => '🇸🇰'],
  ['iso' => 'SL', 'name' => 'Sierra Leone', 'native' => 'Sierra Leone', 'emoji' => '🇸🇱'],
  ['iso' => 'SM', 'name' => 'San Marino', 'native' => 'San Marino', 'emoji' => '🇸🇲'],
  ['iso' => 'SN', 'name' => 'Senegal', 'native' => 'Sénégal', 'emoji' => '🇸🇳'],
  ['iso' => 'SO', 'name' => 'Somalia', 'native' => 'Soomaaliya', 'emoji' => '🇸🇴'],
  ['iso' => 'SR', 'name' => 'Suriname', 'native' => 'Suriname', 'emoji' => '🇸🇷'],
  ['iso' => 'SS', 'name' => 'South Sudan', 'native' => 'South Sudan', 'emoji' => '🇸🇸'],
  ['iso' => 'ST', 'name' => 'São Tomé and Príncipe', 'native' => 'São Tomé e Príncipe', 'emoji' => '🇸🇹'],
  ['iso' => 'SV', 'name' => 'El Salvador', 'native' => 'El Salvador', 'emoji' => '🇸🇻'],
  ['iso' => 'SX', 'name' => 'Sint Maarten', 'native' => 'Sint Maarten', 'emoji' => '🇸🇽'],
  ['iso' => 'SY', 'name' => 'Syria', 'native' => 'سوريا', 'emoji' => '🇸🇾'],
  ['iso' => 'SZ', 'name' => 'Eswatini', 'native' => 'eSwatini', 'emoji' => '🇸🇿'],
  ['iso' => 'TC', 'name' => 'Turks and Caicos Islands', 'native' => 'Turks and Caicos Islands', 'emoji' => '🇹🇨'],
  ['iso' => 'TD', 'name' => 'Chad', 'native' => 'Tchad', 'emoji' => '🇹🇩'],
  ['iso' => 'TF', 'name' => 'French Southern Territories', 'native' => 'Terres australes françaises', 'emoji' => '🇹🇫'],
  ['iso' => 'TG', 'name' => 'Togo', 'native' => 'Togo', 'emoji' => '🇹🇬'],
  ['iso' => 'TH', 'name' => 'Thailand', 'native' => 'ประเทศไทย', 'emoji' => '🇹🇭'],
  ['iso' => 'TJ', 'name' => 'Tajikistan', 'native' => 'Тоҷикистон', 'emoji' => '🇹🇯'],
  ['iso' => 'TK', 'name' => 'Tokelau', 'native' => 'Tokelau', 'emoji' => '🇹🇰'],
  ['iso' => 'TL', 'name' => 'Timor-Leste', 'native' => 'Timor-Leste', 'emoji' => '🇹🇱'],
  ['iso' => 'TM', 'name' => 'Turkmenistan', 'native' => 'Türkmenистан', 'emoji' => '🇹🇲'],
  ['iso' => 'TN', 'name' => 'Tunisia', 'native' => 'تونس', 'emoji' => '🇹🇳'],
  ['iso' => 'TO', 'name' => 'Tonga', 'native' => 'Tonga', 'emoji' => '🇹🇴'],
  ['iso' => 'TR', 'name' => 'Turkey', 'native' => 'Türkiye', 'emoji' => '🇹🇷'],
  ['iso' => 'TT', 'name' => 'Trinidad and Tobago', 'native' => 'Trinidad and Tobago', 'emoji' => '🇹🇹'],
  ['iso' => 'TV', 'name' => 'Tuvalu', 'native' => 'Tuvalu', 'emoji' => '🇹🇻'],
  ['iso' => 'TW', 'name' => 'Taiwan', 'native' => '臺灣', 'emoji' => '🇹🇼'],
  ['iso' => 'TZ', 'name' => 'Tanzania', 'native' => 'Tanzania', 'emoji' => '🇹🇿'],
  ['iso' => 'UA', 'name' => 'Ukraine', 'native' => 'Україна', 'emoji' => '🇺🇦'],
  ['iso' => 'UG', 'name' => 'Uganda', 'native' => 'Uganda', 'emoji' => '🇺🇬'],
  ['iso' => 'UM', 'name' => 'U.S. Minor Outlying Islands', 'native' => 'United States Minor Outlying Islands', 'emoji' => '🇺🇲'],
  ['iso' => 'US', 'name' => 'United States', 'native' => 'United States', 'emoji' => '🇺🇸'],
  ['iso' => 'UY', 'name' => 'Uruguay', 'native' => 'Uruguay', 'emoji' => '🇺🇾'],
  ['iso' => 'UZ', 'name' => 'Uzbekistan', 'native' => 'Oʻzbekiston', 'emoji' => '🇺🇿'],
  ['iso' => 'VA', 'name' => 'Vatican City', 'native' => 'Vaticano', 'emoji' => '🇻🇦'],
  ['iso' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'native' => 'Saint Vincent and the Grenadines', 'emoji' => '🇻🇨'],
  ['iso' => 'VE', 'name' => 'Venezuela', 'native' => 'Venezuela', 'emoji' => '🇻🇪'],
  ['iso' => 'VG', 'name' => 'British Virgin Islands', 'native' => 'British Virgin Islands', 'emoji' => '🇻🇬'],
  ['iso' => 'VI', 'name' => 'U.S. Virgin Islands', 'native' => 'United States Virgin Islands', 'emoji' => '🇻🇮'],
  ['iso' => 'VN', 'name' => 'Vietnam', 'native' => 'Việt Nam', 'emoji' => '🇻🇳'],
  ['iso' => 'VU', 'name' => 'Vanuatu', 'native' => 'Vanuatu', 'emoji' => '🇻🇺'],
  ['iso' => 'WF', 'name' => 'Wallis and Futuna', 'native' => 'Wallis-et-Futuna', 'emoji' => '🇼🇫'],
  ['iso' => 'WS', 'name' => 'Samoa', 'native' => 'Samoa', 'emoji' => '🇼🇸'],
  ['iso' => 'XK', 'name' => 'Kosovo', 'native' => 'Kosovë', 'emoji' => '🇽🇰'],
  ['iso' => 'YE', 'name' => 'Yemen', 'native' => 'اليمن', 'emoji' => '🇾🇪'],
  ['iso' => 'YT', 'name' => 'Mayotte', 'native' => 'Mayotte', 'emoji' => '🇾🇹'],
  ['iso' => 'ZA', 'name' => 'South Africa', 'native' => 'South Africa', 'emoji' => '🇿🇦'],
  ['iso' => 'ZM', 'name' => 'Zambia', 'native' => 'Zambia', 'emoji' => '🇿🇲'],
  ['iso' => 'ZW', 'name' => 'Zimbabwe', 'native' => 'Zimbabwe', 'emoji' => '🇿🇼'],
];